# Q1.

In [2]:
import numpy as np

arr1 = np.random.rand(5,3)
arr2 = np.random.rand(3,2)

dot = np.dot(arr1, arr2)
print(dot)

[[0.07331364 0.48852256]
 [0.07282826 0.44210008]
 [0.10909054 0.55598111]
 [0.02774477 0.11998138]
 [0.10604898 0.57093977]]


# Q2.

In [4]:
import numpy as np

arr1 = np.array([[5, 7], [9, 11]], float)
arr2 = np.array([[2, 4], [6, 8]], float)

concat_1 = np.concatenate((arr1, arr2), axis = 0)
concat_2 = np.concatenate((arr1, arr2), axis = 1)

print(concat_1)
print(concat_2)

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


# Q3.

In [7]:
import numpy as np

xy = np.array([[1., 2., 3., 4., 5., 6.], [10., 20., 30., 40., 50., 60.]])

x_train = np.array(xy[0])
y_train = np.array(xy[1])

print(x_train, x_train.shape)
print(y_train, y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


# Q4.

In [11]:
beta_gd = [np.random.uniform(low=-1.0, high=1.0)]
bias = [np.random.uniform(low=-1.0, high=1.0)]

print(beta_gd, bias)

[-0.5805734666039801] [-0.06904378398525002]


# Q5.

In [20]:
import numpy as np

xy = np.array([[1., 2., 3., 4., 5., 6.], [10., 20., 30., 40., 50., 60.]])

x_train = np.array(xy[0])
y_train = np.array(xy[1])

beta_gd = [np.random.uniform(low=-1.0, high=1.0)]
bias = [np.random.uniform(low=-1.0, high=1.0)]

learning_rate = 0.01
errors = []

for i in range(1000):
    y_hat = x_train * beta_gd + bias

    error = ((y_hat - y_train)**2).mean()
    
    beta_gd = beta_gd - learning_rate * ((y_hat - y_train) * x_train).mean()
    bias = bias - learning_rate * (y_hat - y_train).mean()
    
    errors.append(error)
    
    if i % 100 == 0:
        print('Epoch ({:10d}/1000) error: {:10f}, beta_gd: {:10f}'.format(i, error, beta_gd.item(), bias.item()))

Epoch (         0/1000) error: 1298.706143, beta_gd:   2.275711
Epoch (       100/1000) error:   0.302624, beta_gd:   9.707612
Epoch (       200/1000) error:   0.210022, beta_gd:   9.756421
Epoch (       300/1000) error:   0.145756, beta_gd:   9.797082
Epoch (       400/1000) error:   0.101155, beta_gd:   9.830955
Epoch (       500/1000) error:   0.070202, beta_gd:   9.859174
Epoch (       600/1000) error:   0.048721, beta_gd:   9.882682
Epoch (       700/1000) error:   0.033812, beta_gd:   9.902266
Epoch (       800/1000) error:   0.023466, beta_gd:   9.918581
Epoch (       900/1000) error:   0.016285, beta_gd:   9.932172
