# 1번

In [ ]:
#무작위의 데이터를 가진 두 행렬의 행렬곱 연산 진행
import numpy as np
arr1 = np.random.rand(5, 3)
arr2 = np.random.rand(3, 2)

dot = np.dot(arr1, arr2)

print(dot, dot.shape)

[[1.11744527 1.62012684]
 [1.12247085 1.29787087]
 [1.27447948 1.6836035 ]
 [0.72230217 1.24538264]
 [0.95776147 1.22752243]] (5, 2)


# 2번

In [ ]:
# 두 개의 array를 concatenate axis를 0과 1로 하여 연산
arr1 = np.array([[5, 7], [9, 11]], float)
arr2 = np.array([[2, 4], [6, 8]], float)

concat_1 = np.concatenate((arr1, arr2), axis = 0)
concat_2 = np.concatenate((arr1, arr2), axis = 1)

print(concat_1)
print(concat_2)



[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


# 3번

In [ ]:
#주어진 데이터에서 경사 하강법을 위한 데이터 분리하기
import numpy as np

#2차원 배열에서, 첫 번째 1행은 train, 2행은 test에 해당하므로, 행 인덱스에 따라 분리한다.
xy = np.array([[1., 2., 3., 4., 5., 6.], [10., 20., 30., 40., 50., 60.]])

x_train = xy[0]
y_train = xy[1]

print(x_train, x_train.shape)
print(y_train, y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


# 4번

In [ ]:
#경사 하강법 구현을 위해, weight, bias값을 정의하기
#weight와 bias는 각각 크기가 1인 1차원 벡터로 정의된다.(초기값을 랜덤)

beta_gd = np.random.rand(1,)
bias = np.random.rand(1,)

print(beta_gd, bias)

[0.56755406] [0.65830533]


# 5번

In [ ]:
import numpy as np

xy = np.array([[1., 2., 3., 4., 5., 6.], [3., 6., 9., 12., 15., 18.]])

x_train = xy[0]
y_train = xy[1]

beta_gd = np.random.rand(1,)
bias = np.random.rand(1,)

learning_rate = 0.01

for i in range(1000):
  y_pred = beta_gd * x_train + bias

  #Error는 차이의 제곱을 통해 계산하되, 평균을 내 주어야 한다.
  error = (1/x_train.size * np.sum((y_train - y_pred)**2))**0.5

  dedw = -(1/x_train.size) * np.sum(x_train * (y_train - y_pred)) #에러 계산식을 weight에 대해 편미분한 식
  dedb = -(1/x_train.size) * np.sum(y_train - y_pred) #에러 계산식을 bias에 대해 편미분한 식

  beta_gd = beta_gd - learning_rate * dedw
  bias = bias - learning_rate * dedb

  if i % 100 == 0:
    print('Epoch ({:10d}/1000) error: {:10f}, beta_gd: {:10f}, bias: {:10f}'.format(i, error, beta_gd.item(), bias.item()))


Epoch (         0/1000) error:   9.388810, beta_gd:   0.950226, bias:   0.104243
Epoch (       100/1000) error:   0.202408, beta_gd:   2.892419, bias:   0.460574
Epoch (       200/1000) error:   0.168619, beta_gd:   2.910378, bias:   0.383690
Epoch (       300/1000) error:   0.140472, beta_gd:   2.925339, bias:   0.319641
Epoch (       400/1000) error:   0.117023, beta_gd:   2.937802, bias:   0.266283
Epoch (       500/1000) error:   0.097488, beta_gd:   2.948185, bias:   0.221832
Epoch (       600/1000) error:   0.081214, beta_gd:   2.956834, bias:   0.184801
Epoch (       700/1000) error:   0.067657, beta_gd:   2.964040, bias:   0.153952
Epoch (       800/1000) error:   0.056363, beta_gd:   2.970043, bias:   0.128253
Epoch (       900/1000) error:   0.046954, beta_gd:   2.975044, bias:   0.106844
