# Q1

In [1]:
import numpy as np

arr1 = np.random.rand(5,3)
arr2 = np.random.rand(3,2)

dot = np.dot(arr1, arr2)
print(dot, dot.shape)

[[0.80100301 0.66393379]
 [0.94617535 0.79642344]
 [1.08008929 0.86532568]
 [0.8479606  0.6489572 ]
 [0.41998993 0.29159679]] (5, 2)


# Q2

In [3]:
arr1 = np.array([[5, 7], [9, 11]], float)
arr2 = np.array([[2, 4], [6, 8]], float)

concat_1 = np.concatenate((arr1, arr2), axis=0)
concat_2 = np.concatenate((arr1, arr2), axis=1)

print(concat_1)
print(concat_2)

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


# Q3

In [1]:
import numpy as np

xy = np.array([[1., 2., 3., 4., 5., 6.],
              [10., 20., 30., 40., 50., 60.]])

x_train = xy[0]
y_train = xy[1]

print(x_train, x_train.shape)
print(y_train, y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


# Q4

In [4]:
beta_gd = np.random.rand(1)
bias = np.random.rand(1)

print(beta_gd, bias)

[0.33093737] [0.0307728]
