### Q1

In [6]:
import numpy as np

arr1 = np.random.rand(5,3)
arr2 = np.random.rand(3,2)

dot = np.dot(arr1, arr2)

In [7]:
print(dot, dot.shape)

[[1.62017723 0.68815418]
 [1.09603046 0.29695622]
 [1.36149703 0.59352795]
 [1.97946203 0.87977099]
 [1.69265556 0.8379798 ]] (5, 2)


### Q2

In [17]:
arr1 = np.array([[5, 7], [9, 11]], float)
arr2 = np.array([[2, 4], [6, 8]], float)

In [18]:
concat_1 = np.concatenate((arr1, arr2), axis = 0)
concat_2 = np.concatenate((arr1, arr2), axis = 1)

In [19]:
print(concat_1)

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]


In [20]:
print(concat_2)

[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


### Q3

In [28]:
import numpy as np

xy = np.array([[1., 2., 3., 4., 5., 6.,],
              [10., 20., 30., 40., 50., 60.]])

x_train = xy[0]
y_train = xy[1]

In [29]:
print(x_train, x_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)


In [30]:
print(y_train, y_train.shape)

[10. 20. 30. 40. 50. 60.] (6,)


### Q4

In [59]:
beta_gd = np.random.ranf(1)
bias = np.random.ranf(1)

In [60]:
print(beta_gd, bias)

[0.03840242] [0.45750648]


### Q5

$||X|| = \sqrt {\sum_{i=1}^n{X_i}^2}$

$||y|| = \sqrt {\sum_{i=1}^n{y_i}^2}$

### 예측 함수 

$h(X) = X \times w + b$

### 손실함수

$L(y, h(X)) = {1 \over 2}(h(X)-y)^2 =  {1 \over 2}(h(X)^2 - 2h(X)y + y^2)$

$⇒ {1 \over 2}((X^2w^2 + 2Xwb + b^2) - 2(Xw+b)y + y^2)$

$⇒ {1 \over 2}(X^2w^2 + 2Xwb +b^2 - (2Xw+2b)y + y^2$

${\partial L \over \partial w} = {1 \over 2}(2X^2 + 2Xb - 2Xy) = X^2w + Xb - Xy = X(Xw + b - y)$

$\therefore {\partial L \over \partial w} = X(h(X) - y)$

${\partial L \over \partial b} = {1 \over 2}(2Xw - 2y + 2b) = Xw + b - y$

$\therefore {\partial L \over \partial b} = h(X) - y$

In [35]:
import numpy as np
from numpy import random

xy = np.array([[1., 2., 3., 4., 5., 6.], [3., 6., 9., 12., 15., 18.]])

x_train = xy[0]
y_train = xy[1]

beta_gd = random.ranf(1)
bias = random.ranf(1)

learning_rate = 0.01

n = len(x_train)

def loss_function(X, w, b):
    return X * w + b

for i in range(1000):
    error = (loss_function(x_train, beta_gd, bias) - y_train) ** 2

    cost = np.sum(error) / n

    gradient_w = np.sum((loss_function(x_train, beta_gd, bias) - y_train) * x_train)
    gradient_b = np.sum((loss_function(x_train, beta_gd, bias) - y_train))

    beta_gd -= learning_rate * gradient_w
    bias -= learning_rate * bias

    if i % 100 == 0:
        print('Epoch ({:10d})/1000) error: {:10f}, beta_gd: {:10f}, bias: {:10f}'.format(i, cost, beta_gd.item(), bias.item()))

Epoch (         0)/1000) error:  54.197909, beta_gd:   2.691518, bias:   0.593983
Epoch (       100)/1000) error:   0.009280, beta_gd:   2.949269, bias:   0.217417
Epoch (       200)/1000) error:   0.001243, beta_gd:   2.981431, bias:   0.079582
Epoch (       300)/1000) error:   0.000167, beta_gd:   2.993203, bias:   0.029129
Epoch (       400)/1000) error:   0.000022, beta_gd:   2.997512, bias:   0.010662
Epoch (       500)/1000) error:   0.000003, beta_gd:   2.999089, bias:   0.003903
Epoch (       600)/1000) error:   0.000000, beta_gd:   2.999667, bias:   0.001429
Epoch (       700)/1000) error:   0.000000, beta_gd:   2.999878, bias:   0.000523
Epoch (       800)/1000) error:   0.000000, beta_gd:   2.999955, bias:   0.000191
Epoch (       900)/1000) error:   0.000000, beta_gd:   2.999984, bias:   0.000070


In [33]:
(loss_function(x_train, beta_gd, bias) - y_train)

array([ 2.83129738e-05,  1.90227793e-05,  9.73258475e-06,  4.42390215e-07,
       -8.84780431e-06, -1.81379988e-05])