Q4.

'''  
경사 하강법 구현을 위해서   
  1. 위에서 분리한 x_train 데이터와 계산될 weight, bias 값을 정의해보세요.   
    - 여기서 구현한 weight와 bias 는 linear regression 계산을 진행할시,   
      직선의 기울기와 y 절편의 값이 됩니다.  

    - numpy 내의 random 함수를 이용해보세요.
'''  

beta_gd = # TODO  
bias = # TODO  

[출력 예시]  
print(beta_gd, bias)  

- random 값이여서 값이 다를 수 있음. 같은 형태로 나오면 됨  
[0.75373235] [0.94214468]  

# *  myself

In [1]:
import numpy as np

In [3]:
xy = np.array([[1.,2.,3.,4.,5.,6.], [10.,20.,30.,40.,50.,60]])

In [4]:
x_train = xy[0]
y_train = xy[1]

In [5]:
print(x_train, x_train.shape)  
print(y_train, y_train.shape) 

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


In [6]:
beta_gd = np.random.rand(1)
beta_gd

array([0.6507768])

In [7]:
bias = np.random.rand(1)
bias

array([0.43477926])

In [8]:
print(beta_gd, bias) 

[0.6507768] [0.43477926]


# * another

In [12]:
# 1) 배열 생성 X, 값만 추출
beta_gd, bias = np.random.uniform(0, 1, 2)
print(beta_gd, bias) 

0.7368990766188431 0.017705283658626114
