# Q2.  
  
'''  
두번째로는 numpy에서 자주 사용하는 concatenate 연산에 대한 미션을 수행해보겠습니다.   

 1. 이제 Numpy에서 사용하는 2개의 numpy array가 있을때,   
 2. 두 numpy array의 concatenate 연산을 구해보세요.    

  - axis는 0, 1 두개로 연산한 결과를 출력해보세요.  
  - 각 데이터가 어떤 형태로 더해지는지 확인해보세요.  
    
''' 

arr1 = np.array([[5, 7], [9, 11]], float)  
arr2 = np.array([[2, 4], [6, 8]], float)  

concat_1 = # TODO axis 0  
concat_2 = # TODO axis 1  

[출력 예시]  

[[5. 7.]  
 [9. 11.]  
 [2. 4.]  
 [6. 8.]]  
[[5. 7. 2. 4.]  
 [9. 11. 6. 8.]]   

# *myself

In [1]:
import numpy as np

In [2]:
arr1 = np.array([[5, 7], [9, 11]], float)
arr2 = np.array([[2, 4], [6, 8]], float)

In [6]:
concat_1 = np.concatenate((arr1, arr2), axis=0)
concat_1

array([[ 5.,  7.],
       [ 9., 11.],
       [ 2.,  4.],
       [ 6.,  8.]])

In [7]:
concat_2 = np.concatenate((arr1, arr2), axis=1)
concat_2

array([[ 5.,  7.,  2.,  4.],
       [ 9., 11.,  6.,  8.]])

In [8]:
print(concat_1)
print(concat_2)

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]
