In [1]:
import numpy as np

# 1. operation in array

In [2]:
test_array = np.arange(1, 11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
test_array.sum(dtype=np.float64)

55.0

In [5]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array.sum()

78

In [9]:
test_array.sum(axis=1)

array([10, 26, 42])

In [10]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [7]:
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [8]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])