In [1]:
import numpy as np

# 1. all & any

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [3]:
np.any(a>5), np.any(a<0)

(True, False)

In [4]:
np.all(a>5), np.all(a<10)

(False, True)

# 2. Comparison operation #2

In [6]:
a = np.array([1,3,0], float)
np.logical_and(a>0, a<3)

array([ True, False, False])

In [7]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [8]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True])

# 3. np.where

In [9]:
np.where(a > 0, 3, 2)

array([3, 3, 2])

In [13]:
np.where(a > 0)

(array([0, 2], dtype=int64),)

In [10]:
a = np.arange(10)
np.where(a > 5)

(array([6, 7, 8, 9], dtype=int64),)

In [11]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [12]:
np.isfinite(a)

array([ True, False, False])

# 4. argmax & argmin

In [14]:
# index를 반환
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])
np.argmax(a), np.argmin(a)

(5, 0)

In [15]:
# axis 기반의 반환
a = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])
np.argmax(a, axis = 1), np.argmin(a, axis = 0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))