In [ ]:
import tensorflow as tf

input_shape = (3, 2, 1)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv1D(
    filters=1, kernel_size=2, activation=None, kernel_initializer = 'ones',
    input_shape=input_shape[1:])(x)

print("input ", x)
print("\nconv1D : ", y)

input  tf.Tensor(
[[[-0.16043147]
  [ 0.02068557]]

 [[ 0.385394  ]
  [ 0.5096423 ]]

 [[ 1.0090989 ]
  [-0.25729242]]], shape=(3, 2, 1), dtype=float32)

conv1D :  tf.Tensor(
[[[-0.1397459 ]]

 [[ 0.89503634]]

 [[ 0.7518065 ]]], shape=(3, 1, 1), dtype=float32)


In [ ]:
input_shape = (3, 3, 1)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv1D(
    filters=2, kernel_size=2, activation=None, kernel_initializer = 'ones',
    input_shape=input_shape[1:])(x)

print("input ", x)
print("\nconv1D : ", y)

input  tf.Tensor(
[[[-1.3343631 ]
  [ 0.26213557]
  [-0.52546805]]

 [[ 0.29413816]
  [-1.7074261 ]
  [-0.42327222]]

 [[ 1.3521407 ]
  [-0.25541195]
  [ 1.1116533 ]]], shape=(3, 3, 1), dtype=float32)

conv1D :  tf.Tensor(
[[[-1.0722275  -1.0722275 ]
  [-0.2633325  -0.2633325 ]]

 [[-1.4132879  -1.4132879 ]
  [-2.1306982  -2.1306982 ]]

 [[ 1.0967287   1.0967287 ]
  [ 0.85624135  0.85624135]]], shape=(3, 2, 2), dtype=float32)


In [ ]:
input_shape = (3, 5, 5, 1)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(
    filters=2, kernel_size=2, activation=None, kernel_initializer = 'ones',
    input_shape=input_shape[1:])(x)

print("input ", x)
print("\nconv1D : ", y)

input  tf.Tensor(
[[[[ 1.1663907 ]
   [-0.73557085]
   [ 1.0567178 ]
   [-0.29863405]
   [-1.7357682 ]]

  [[-0.31774753]
   [-2.2190008 ]
   [-1.4366355 ]
   [-0.45643207]
   [ 0.6199039 ]]

  [[ 0.45060915]
   [-0.56656545]
   [-2.5984416 ]
   [-0.15857461]
   [-0.32885653]]

  [[ 1.8410877 ]
   [ 1.5904344 ]
   [-0.4629122 ]
   [-0.578938  ]
   [-0.18785362]]

  [[ 0.09754331]
   [-1.630405  ]
   [-0.07484648]
   [ 1.4707704 ]
   [-0.3384815 ]]]


 [[[-0.77871984]
   [ 0.06237776]
   [ 0.05487884]
   [-0.3247633 ]
   [-1.4655157 ]]

  [[ 0.02473714]
   [ 0.1538733 ]
   [ 0.97484684]
   [ 0.2842002 ]
   [-0.2369323 ]]

  [[-0.08187184]
   [ 0.31743228]
   [-1.012833  ]
   [-0.36347282]
   [-1.7295719 ]]

  [[-1.4731363 ]
   [ 0.7413074 ]
   [-1.1012523 ]
   [ 0.8155328 ]
   [ 0.19208501]]

  [[ 0.16665916]
   [-1.1396301 ]
   [-0.10381007]
   [-0.7636004 ]
   [ 0.59770143]]]


 [[[-0.06723111]
   [ 0.09477233]
   [-0.9709917 ]
   [ 0.04903078]
   [-0.9273417 ]]

  [[-0.34274566]
   [