In [ ]:
import tensorflow as tf
from tensorflow.keras import layers

class exDense(layers.Layer):

  def __init__(self, units=32):
      super(exDense, self).__init__()
      self.units = units

  def build(self, input_shape):
    w_init = tf.random_normal_initializer()
    self.w = tf.Variable(
        initial_value=w_init(shape=(input_shape[-1], self.units),
                             dtype='float32'), trainable=True, name="weight")
    b_init = tf.ones_initializer()
    self.b = tf.Variable(
        initial_value=b_init(shape=(self.units,), dtype='float32'),
        trainable=False, name="bias")

  def call(self, inputs):
      return tf.matmul(inputs, self.w) + self.b

In [ ]:
# 레이어 인스턴스 생성.
exDense_layer = exDense(4)

# build() 호출 전의 가중치 확인
before_w = exDense_layer.weights
print("all weights(before)", before_w)

# 입력 데이터 대입 및 결과 반환
out = exDense_layer(tf.ones((3, 3)))
print("\noutputs:", out)

# build() 호출 후의 가중치 확인
after_w = exDense_layer.weights
print("\nall weights(after)", after_w)

all weights(before) []

outputs: tf.Tensor(
[[0.9748206 0.9446439 1.0575922 0.752672 ]
 [0.9748206 0.9446439 1.0575922 0.752672 ]
 [0.9748206 0.9446439 1.0575922 0.752672 ]], shape=(3, 4), dtype=float32)

all weights(after) [<tf.Variable 'ex_dense_2/weight:0' shape=(3, 4) dtype=float32, numpy=
array([[-0.05319884,  0.02535464,  0.02014052, -0.05885068],
       [-0.05355629, -0.05616728,  0.0636033 , -0.117639  ],
       [ 0.08157578, -0.02454344, -0.02615165, -0.07083832]],
      dtype=float32)>, <tf.Variable 'ex_dense_2/bias:0' shape=(4,) dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>]


In [ ]:
t_w = exDense_layer.trainable_weights
print("\ntraninable_weights", t_w)

nt_w = exDense_layer.non_trainable_weights
print("\nnon_traninable_weights", nt_w)

t_v = exDense_layer.trainable_variables
print("\ntraninable_variables", t_v)

nt_v = exDense_layer.non_trainable_variables
print("\nnon_traninable_variables", nt_v)




traninable_weights [<tf.Variable 'ex_dense_2/weight:0' shape=(3, 4) dtype=float32, numpy=
array([[-0.05319884,  0.02535464,  0.02014052, -0.05885068],
       [-0.05355629, -0.05616728,  0.0636033 , -0.117639  ],
       [ 0.08157578, -0.02454344, -0.02615165, -0.07083832]],
      dtype=float32)>]

non_traninable_weights [<tf.Variable 'ex_dense_2/bias:0' shape=(4,) dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>]

traninable_variables [<tf.Variable 'ex_dense_2/weight:0' shape=(3, 4) dtype=float32, numpy=
array([[-0.05319884,  0.02535464,  0.02014052, -0.05885068],
       [-0.05355629, -0.05616728,  0.0636033 , -0.117639  ],
       [ 0.08157578, -0.02454344, -0.02615165, -0.07083832]],
      dtype=float32)>]

non_traninable_variables [<tf.Variable 'ex_dense_2/bias:0' shape=(4,) dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>]


In [ ]:
import tensorflow as tf
from tensorflow.keras import layers

class exDense(layers.Layer):

  def __init__(self, units=32):
      super(exDense, self).__init__()
      self.units = units

  def build(self, input_shape):
    self.w = self.add_weight(shape=(input_shape[-1], self.units),
                          initializer='random_normal',
                          trainable=True, name="weight")
    self.b = self.add_weight(shape=(self.units,),
                              initializer='random_normal',
                              trainable=True, name="bias")
  def call(self, inputs):
      return tf.matmul(inputs, self.w) + self.b